home/urls.py
from django.urls import path
from . import views
app_name = 'result'
urlpatterns = [

    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('marks/<int:selected_semester>/',views.marks_table, name='marks'),
    path('logout/', views.log, name='log')

]

result_processing_system/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from home.views import home, student_info

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', home, name='home')

]

home/models.py
from django.db import models
from django.core.validators import MaxValueValidator

# Create your models here.
class Semester(models.Model):
    sem = (
        ('1st Semester', '1st Semester'),
        ('2nd Semester', '2nd Semester'),
        ('3rd Semester', '3rd Semester'),
        ('4th Semester', '4th Semester'),
        ('5th Semester', '5th Semester'),
        ('6th Semester', '6th Semester'),
        ('7th Semester', '7th Semester'),
        ('8th Semester', '8th Semester')
    )

    student_semester = models.CharField(max_length=15, choices=sem,unique=True)

    def __str__(self):
        return self.student_semester


class Informations(models.Model):
    department = (
        ('CSE', 'CSE'),
        ('ECE', 'ECE'),
        ('BBA', 'BBA')
    )

    student_roll = models.PositiveIntegerField(default=0)
    student_department = models.CharField(max_length=4, choices=department)

    class Meta:
        unique_together = (('student_roll', 'student_department'),)

    def __str__(self):
        return self.student_department+', '+self.student_roll.__str__()


class Marks(models.Model):
    student_info = models.ForeignKey(Informations, on_delete=models.CASCADE)
    all_semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=50)
    subject_marks = models.PositiveIntegerField(default=0,validators=[MaxValueValidator(100)])
    assignment_marks = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5)])
    midterm_marks = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(10)])
    class_test_marks = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5)])

    class Meta(object):
        unique_together = (('student_info','subject_name'),)
        ordering = ['all_semester']

    def __str__(self):
        return self.subject_name+', '+self.subject_marks.__str__()+', '+self.assignment_marks.__str__()+', '+self.midterm_marks.__str__()+', '+self.class_test_marks.__str__()+', '+self.student_info.student_roll.__str__()+', '+self.all_semester.student_semester+', '+self.student_info.student_department

home/views.py
from django.shortcuts import render, redirect
from .models import Marks, Semester
from django.contrib.auth import authenticate, login as dj_login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def login(request):

    if request.user.is_authenticated:
        return redirect('result:home')
    else:
        if request.method == 'POST':
            username = request.POST['user']
            password = request.POST['pass']

            request.session['username'] = request.POST['user']
            request.session['password'] = request.POST['pass']

            try:
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    if user.is_active:
                        dj_login(request, user)
                        return redirect('result:home')
                else:
                    messages.error(request, 'Username and Password not match')
            except ObjectDoesNotExist:
                print("invalid User")
        return render(request, 'login.html')


@login_required(login_url='result:login')
def home(request):
    password = request.session['password']
    context = {
        'semester': Semester.objects.all(),
        'dept': request.session['username'],
        'roll': password[4:8]
    }
    if request.method == 'POST':
        selected_semester = 0
        selected_semester = request.POST['semester']
        if selected_semester != 0:
            return redirect('result:marks', selected_semester)

    return render(request, 'FrontPage.html', context)



@login_required(login_url='result:login')
def marks_table(request, selected_semester):
    print(selected_semester,type(selected_semester))
    dept = request.session['username']
    roll = request.session['password']
    roll = roll[4:8]

    all_marks = Marks.objects.filter(all_semester__id=selected_semester).filter(student_info__student_roll=roll).filter(student_info__student_department=dept)

    if len(all_marks)!=0:
        total = []
        point = []
        for i in range(0, len(all_marks)):
            t = all_marks[i].subject_marks + all_marks[i].assignment_marks + all_marks[i].class_test_marks + all_marks[i].midterm_marks
            total.append(t)
            if t >= 80:
                point.append(4.00)
            elif t<80 and t >= 75:
                point.append(3.75)
            elif t < 75 and t >= 70:
                point.append(3.50)
            elif t < 70 and t >= 65:
                point.append(3.25)
            elif t < 65 and t >= 60:
                point.append(3.00)
            elif t < 60 and t >= 55:
                point.append(2.75)
            elif t < 55 and t >= 50:
                point.append(2.50)
            elif t < 50 and t >= 45:
                point.append(2.25)
            elif t < 45 and t >= 40:
                point.append(2.00)
            else:
                point.append(0.00)

        if selected_semester == 1:
            gpa = sum(point)*3/16.5
        elif selected_semester == 2:
            gpa = sum(point)*3/18
        elif selected_semester == 3:
            gpa = sum(point)*3/22.5
        elif selected_semester == 4:
            gpa = sum(point)*3/18.0
        elif selected_semester == 5:
            gpa = sum(point)*3/16.5
        elif selected_semester == 6:
            gpa = sum(point)*3/19.5
        elif selected_semester == 7:
            gpa = sum(point)*3/17.5
        elif selected_semester == 8:
            gpa = sum(point) * 3 / 16.5

        gpa = format(gpa, '.2')
        context = {
            'all_student': list(zip(total, point, all_marks)),
            'gpa': gpa
        }
        return render(request, 'student_table.html', context)

    else:
        context = {
            'all_student': all_marks
        }
        return render(request, 'student_table.html', context)



def log(request):
    logout(request)
    return redirect('result:login')

home/templates/FrontPage.html
<!DOCTYPE html>

<html>
<head>
	<title>Result Processing System</title>
	<meta charset="utf-8">
	<!-- Loads the path to static file -->
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'home/FrontPage.css' %}" />
</head>
<body>

	<div id="text">
        <h1>RESULT PROCESSING SYSTEM</h1>
	</div>

    <li><a href="{% url 'result:log' %}">Logout</a></li>

    <div class="col-sm-4"><br>
        <div id="select">
            <p>{{ dept}}</p>
            <p>{{ roll }}</p>
            <form action="" method="post">
                {% csrf_token %}
                <select class="form-control" id="" name="semester">
                    <option disabled>Select Semester</option>
                    {% for s in semester%}
                        <option value="{{ s.id }}">{{ s.student_semester }}</option>
                    {% endfor %}
                </select>
                <button>Submit</button>
            </form>
        </div>
    </div>
</body>
</html>

home/templates/login.html
	<div class="container">
        <div class="form-group cl-md-4">
            {% if messages %}
            <ul class="message">
                {% for message in messages %}
                    <li class="alert alert-danger">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
		<div class="row">
			<div class="col-sm-4">
				<div class="panel panel-danger">
					<div class="panel panel-heading">Login Form</div>
                    <div class="panel-body">
						<form method="post" action="" >
                            {% csrf_token %}
							<div class="form-group">
								<label for="username">Username:</label>
								<input type="text" name="user" class="form-control" id="username" required placeholder="Enter Username"/>
							</div>
							<div class="form-group">
								<label for="pwd1">Password:</label>
								<input type="password" name="pass"  class="form-control" id="pwd1" required placeholder="Enter password"/>
							</div>
							<button type="submit" class="btn btn-default">Submit</button>
						</form>
                    </div>
					</div>
				</div>
		</div>
	</div>

home/templates/marks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Marks</title>
</head>
<body>
    <form method="post" action="#">
        <lebel>Name: </lebel>
        <input type="text" name="name"> <br>
        <lebel>Marks: </lebel>
        <input type="text" name="number"><br>
        <button type="submit" name="save">Save</button>

    </form>

</body>
</html>

home/templates/student_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>student Info</title>
</head>
<body>
    <style>
        table, th, td{
            border: 1px solid black;
        }
    </style>
    <table>
    <li><a href="{% url 'result:log' %}">Logout</a></li>

        {% if all_student|length %}

        <tr>
            <th>Student Name</th>
            <th>Subject Mark</th>
            <th>Assignment Mark</th>
            <th>Midterm Mark</th>
            <th>Class Test Mark</th>
            <th>Total Marks</th>
            <th>GPA</th>
        </tr>
         {% for i,j,student in all_student %}
         <tr>
            <td>{{student.subject_name}}</td>
            <td>{{student.subject_marks}}</td>
            <td>{{student.assignment_marks}}</td>
            <td>{{student.midterm_marks}}</td>
            <td>{{student.class_test_marks}}</td>
            <td>{{ i }}</td>
            <td>{{ j }}</td>
        </tr>


        {% endfor %}
            <tr>
            <th>Total GPA = {{gpa }}</th>
        </tr>
        {% else %}
        <p>This semester result are not published</p>

    {% endif %}
    </table>

</body>
</html>

home/templates/teacher_table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teachers</title>
</head>
<body>
     <table>
        <thead>
        <tr>
            <th>Teachers Name</th>
            <th>Address</th>
            <th>Department</th>
        </tr>
        </thead>
        {% for teacher in all_teacher %}
        <tbody>
            <tr>
            <td>{{teacher.teacher_name}}</td>
            <td>{{teacher.address}}</td>
            <td>{{teacher.dept}}</td>
        </tr>
        </tbody>
        {% endfor %}

    </table>


</body>
</html>